version: "3.9"
services:
  api:
    image: gogotechhk/gogobot-log-api:0.2.0
    ports:
      - "8081:8081"
    container_name: gogobot-log-api
  db:
    image: postgres
    ports:
      - 5432:5432
    container_name: gogobot-log-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: CHANGE_ME
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - ./:/var/lib/postgresql/data/

  
